version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles  # 👈 Add this
    environment:
      - DEBUG=True

volumes:
  media_volume:
  static_volume:  # 👈 Add this
