# Generated by Django 5.2.4 on 2025-07-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='excelaccess',
            unique_together={('doctor', 'excel_file')},
        ),
    ]
