# Generated by Django 5.2.4 on 2025-07-09 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_excelaccess_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='matched_records',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='searched_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excelaccess',
            name='allowed_columns',
            field=models.JSONField(default=list),
        ),
    ]
